import { JWT } from "google-auth-library";
import { GoogleSpreadsheet } from "google-spreadsheet";

export const accessSpreadsheet=async()=>{
    const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: '',
        key: "",
        scopes: [
          'https://www.googleapis.com/auth/spreadsheets',
        ],
      });
    const doc = new GoogleSpreadsheet('1_WGUR22JDH9QjsUfW_GPFd_b2k2yYqyTHsHwTIW7jbY',serviceAccountAuth);

    // Load the spreadsheet
    await doc.loadInfo();

    // Access a specific sheet
    const sheet = doc.sheetsByIndex[0];

    // Fetch rows from the sheet
    const rows = await sheet.getRows();
    return rows;
}